import type Database from 'better-sqlite3';
import { getDb } from './db';
import { writeDialplanFile, signalAsteriskReload } from './dialplan';
import { callerIdMatchExpr } from './ivr';

export interface BlacklistEntry {
  number: string;
  reason: string | null;
  hits: number;
  createdAt: string;
  updatedAt: string;
}

export class InvalidBlacklistError extends Error {}

// 数字 + 前方一致用 * (IVR caller-id route と同じ表現)。
const NUMBER_RE = /^[0-9+*]{2,20}$/;

interface Row {
  number: string;
  reason: string | null;
  hits: number;
  created_at: string;
  updated_at: string;
}

function rowTo(r: Row): BlacklistEntry {
  return { number: r.number, reason: r.reason, hits: r.hits, createdAt: r.created_at, updatedAt: r.updated_at };
}

export function listBlacklist(db: Database.Database = getDb()): BlacklistEntry[] {
  return (
    db.prepare('SELECT number, reason, hits, created_at, updated_at FROM blacklist ORDER BY number').all() as Row[]
  ).map(rowTo);
}

export function getBlacklistEntry(number: string, db: Database.Database = getDb()): BlacklistEntry | null {
  const r = db
    .prepare('SELECT number, reason, hits, created_at, updated_at FROM blacklist WHERE number = ?')
    .get(number) as Row | undefined;
  return r ? rowTo(r) : null;
}

export interface AddBlacklistInput {
  number: string;
  reason?: string | null;
}

function validate(number: string): void {
  if (!NUMBER_RE.test(number)) {
    throw new InvalidBlacklistError('番号は数字 / + / * のみ (末尾 * で前方一致、2〜20 文字)');
  }
}

// 既存番号は理由を上書きする (CDR からのワンクリック追加を冪等にするため)。
export function addToBlacklist(input: AddBlacklistInput, db: Database.Database = getDb()): BlacklistEntry {
  const number = input.number.trim();
  validate(number);
  db.prepare(
    `INSERT INTO blacklist (number, reason, updated_at) VALUES (?, ?, datetime('now'))
     ON CONFLICT(number) DO UPDATE SET reason = excluded.reason, updated_at = datetime('now')`,
  ).run(number, input.reason?.trim() || null);
  return getBlacklistEntry(number, db)!;
}

export function deleteBlacklistEntry(number: string, db: Database.Database = getDb()): boolean {
  return db.prepare('DELETE FROM blacklist WHERE number = ?').run(number).changes > 0;
}

// dialplan.d/blacklist.conf を全エントリから再生成する。
// [blacklist-check] は from-trunk の Gosub から呼ばれる。エントリが空でも
// `exten => s,1,...,Return()` を必ず出力し、Gosub が失敗しないようにする。
export function renderBlacklistDialplan(entries: BlacklistEntry[] = listBlacklist()): string {
  const lines: string[] = [];
  lines.push('; AUTO-GENERATED by Web (/blacklist). 手で編集しないこと。');
  lines.push(`; updated_at: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('[blacklist-check]');
  lines.push('exten => s,1,NoOp(blacklist check ${CALLERID(num)})');
  for (const e of entries) {
    lines.push(` same => n,GotoIf(${callerIdMatchExpr(e.number)}?blacklist-check,blocked,1)`);
  }
  lines.push(' same => n,Return()');
  lines.push('');
  lines.push('exten => blocked,1,NoOp(blocked caller ${CALLERID(num)})');
  lines.push(' same => n,Hangup()');
  lines.push('');
  return lines.join('\n');
}

export async function writeBlacklistDialplanAndReload(): Promise<void> {
  await writeDialplanFile('blacklist.conf', renderBlacklistDialplan());
  await signalAsteriskReload();
}
