import type Database from 'better-sqlite3';
import path from 'node:path';
import fs from 'node:fs/promises';
import { getDb } from './db';
import { pickupGroupsOf } from './pickupGroups';
import { getNetworkSettings } from './network';

export interface Extension {
  number: string;
  displayName: string | null;
  secret: string;
  note: string | null;
  webrtc: boolean;
  updatedAt: string;
}

export class InvalidExtensionError extends Error {}

const NUMBER_RE = /^[0-9]{2,6}$/; // 内線番号: 2〜6桁の数字
const PJSIP_OUT_DIR = process.env.PJSIP_OUT_DIR ?? '/asterisk/pjsip.d';
const DIALPLAN_OUT_DIR = process.env.DIALPLAN_OUT_DIR ?? '/asterisk/dialplan.d';
const ASTERISK_SIGNAL_DIR = process.env.ASTERISK_SIGNAL_DIR ?? '/asterisk/signals';

interface ExtensionRow {
  number: string;
  display_name: string | null;
  secret: string;
  note: string | null;
  updated_at: string;
  webrtc?: number;
}

function rowToExtension(r: ExtensionRow): Extension {
  return {
    number: r.number,
    displayName: r.display_name,
    secret: r.secret,
    note: r.note,
    webrtc: !!r.webrtc,
    updatedAt: r.updated_at,
  };
}

export function listExtensions(db: Database.Database = getDb()): Extension[] {
  const rows = db
    .prepare('SELECT number, display_name, secret, note, webrtc, updated_at FROM extensions ORDER BY number')
    .all() as ExtensionRow[];
  return rows.map(rowToExtension);
}

export function getExtension(number: string, db: Database.Database = getDb()): Extension | null {
  const row = db
    .prepare('SELECT number, display_name, secret, note, webrtc, updated_at FROM extensions WHERE number = ?')
    .get(number) as ExtensionRow | undefined;
  return row ? rowToExtension(row) : null;
}

export interface UpsertExtensionInput {
  number: string;
  displayName?: string;
  secret: string;
  note?: string;
  webrtc?: boolean;
}

function validate(input: UpsertExtensionInput): void {
  if (!NUMBER_RE.test(input.number)) {
    throw new InvalidExtensionError('number は 2〜6 桁の数字で指定してください');
  }
  if (!input.secret || input.secret.length < 4) {
    throw new InvalidExtensionError('secret (パスワード) は 4 文字以上で必須です');
  }
  if (/["\\\n\r]/.test(input.secret)) {
    throw new InvalidExtensionError('secret に " \\ 改行は使えません');
  }
}

export function createExtension(input: UpsertExtensionInput, db: Database.Database = getDb()): Extension {
  validate(input);
  if (getExtension(input.number, db)) {
    throw new InvalidExtensionError(`内線 ${input.number} は既に存在します`);
  }
  db.prepare(
    `INSERT INTO extensions (number, display_name, secret, note, webrtc, updated_at)
     VALUES (?, ?, ?, ?, ?, datetime('now'))`,
  ).run(input.number, input.displayName ?? null, input.secret, input.note ?? null, input.webrtc ? 1 : 0);
  return getExtension(input.number, db)!;
}

export function updateExtension(input: UpsertExtensionInput, db: Database.Database = getDb()): Extension {
  validate(input);
  const existing = getExtension(input.number, db);
  if (!existing) {
    throw new InvalidExtensionError(`内線 ${input.number} は存在しません`);
  }
  db.prepare(
    `UPDATE extensions
        SET display_name = ?, secret = ?, note = ?, webrtc = ?, updated_at = datetime('now')
      WHERE number = ?`,
  ).run(input.displayName ?? null, input.secret, input.note ?? null, input.webrtc ? 1 : 0, input.number);
  return getExtension(input.number, db)!;
}

export function deleteExtension(number: string, db: Database.Database = getDb()): boolean {
  if (!NUMBER_RE.test(number)) {
    throw new InvalidExtensionError('number 形式が不正です');
  }
  const info = db.prepare('DELETE FROM extensions WHERE number = ?').run(number);
  return info.changes > 0;
}

// PJSIP transport セクション (UDP/TCP/WSS) を生成する。
// Docker Desktop 上ではスマホや Tailnet の CIDR を local_net に入れると
// external_* の書き換えが止まりやすい。通常は external_* のみを設定し、
// local_net は Asterisk から直接到達できるネットワークに限る。
export function renderTransportConfig(): string {
  const net = getNetworkSettings();
  const lines: string[] = [];
  lines.push('; AUTO-GENERATED by Web (/network). 手で編集しないこと。');
  lines.push(`; updated_at: ${new Date().toISOString()}`);
  lines.push('');

  const renderExtras = () => {
    const out: string[] = [];
    if (net.externalIp) out.push(`external_media_address=${net.externalIp}`);
    const sig = net.externalSignalingIp ?? net.externalIp;
    if (sig) out.push(`external_signaling_address=${sig}`);
    if (net.localNet) {
      // カンマ区切り → 複数行 local_net= に分解
      for (const cidr of net.localNet.split(',').map((c) => c.trim()).filter(Boolean)) {
        out.push(`local_net=${cidr}`);
      }
    }
    return out;
  };

  // UDP
  lines.push('[transport-udp]');
  lines.push('type=transport');
  lines.push('protocol=udp');
  lines.push('bind=0.0.0.0:5060');
  lines.push('allow_reload=yes');
  for (const e of renderExtras()) lines.push(e);
  lines.push('');

  // TCP
  lines.push('[transport-tcp]');
  lines.push('type=transport');
  lines.push('protocol=tcp');
  lines.push('bind=0.0.0.0:5060');
  lines.push('allow_reload=yes');
  for (const e of renderExtras()) lines.push(e);
  lines.push('');

  // WSS (WebRTC)
  lines.push('[transport-wss]');
  lines.push('type=transport');
  lines.push('protocol=wss');
  lines.push('bind=0.0.0.0:8089');
  lines.push('allow_reload=yes');
  lines.push('cert_file=/etc/asterisk/certs/asterisk.pem');
  lines.push('priv_key_file=/etc/asterisk/certs/asterisk.key');
  for (const e of renderExtras()) lines.push(e);
  lines.push('');

  // 内線エンドポイント用テンプレート群 (旧 pjsip.conf にあったもの)
  lines.push('[endpoint-internal](!)');
  lines.push('type=endpoint');
  lines.push('context=internal');
  lines.push('disallow=all');
  lines.push('allow=ulaw');
  lines.push('allow=alaw');
  lines.push('allow=opus');
  lines.push('direct_media=no');
  lines.push('rtp_symmetric=yes');
  lines.push('force_rport=yes');
  lines.push('rewrite_contact=yes');
  lines.push('');

  lines.push('[endpoint-webrtc](!)');
  lines.push('type=endpoint');
  lines.push('context=internal');
  lines.push('disallow=all');
  lines.push('allow=opus');
  lines.push('allow=ulaw');
  lines.push('allow=alaw');
  lines.push('webrtc=yes');
  lines.push('use_avpf=yes');
  lines.push('media_use_received_transport=yes');
  lines.push('rtcp_mux=yes');
  lines.push('dtls_auto_generate_cert=yes');
  lines.push('dtls_verify=fingerprint');
  lines.push('ice_support=yes');
  lines.push('transport=transport-wss');
  lines.push('direct_media=no');
  lines.push('rtp_symmetric=yes');
  lines.push('force_rport=yes');
  lines.push('rewrite_contact=yes');
  lines.push('');

  lines.push('[auth-userpass](!)');
  lines.push('type=auth');
  lines.push('auth_type=userpass');
  lines.push('');

  lines.push('[aor-single](!)');
  lines.push('type=aor');
  lines.push('max_contacts=1');
  lines.push('remove_existing=yes');
  lines.push('qualify_frequency=30');
  lines.push('');

  return lines.join('\n');
}

// Asterisk の pjsip.d/extensions.conf を再生成する。
export async function renderPjsipConfig(): Promise<string> {
  const rows = listExtensions();
  const blocks: string[] = [
    '; AUTO-GENERATED by Web (/extensions). 手で編集しないこと。',
    `; updated_at: ${new Date().toISOString()}`,
    '',
  ];
  for (const e of rows) {
    const cidName = (e.displayName ?? `Ext ${e.number}`).replace(/"/g, '');
    const pickupNames = pickupGroupsOf(e.number);
    const templateName = e.webrtc ? 'endpoint-webrtc' : 'endpoint-internal';
    blocks.push(`[${e.number}](${templateName})`);
    blocks.push(`auth=auth${e.number}`);
    blocks.push(`aors=${e.number}`);
    blocks.push(`callerid="${cidName}" <${e.number}>`);
    if (pickupNames.length > 0) {
      blocks.push(`named_call_group=${pickupNames.join(',')}`);
      blocks.push(`named_pickup_group=${pickupNames.join(',')}`);
    }
    blocks.push('');
    blocks.push(`[auth${e.number}](auth-userpass)`);
    blocks.push(`username=${e.number}`);
    blocks.push(`password=${e.secret}`);
    blocks.push('');
    blocks.push(`[${e.number}](aor-single)`);
    blocks.push('');
  }
  return blocks.join('\n');
}

export async function writePjsipConfigAndReload(): Promise<{ path: string; reloaded: boolean }> {
  await fs.mkdir(PJSIP_OUT_DIR, { recursive: true });
  // transports.conf (Tailscale 等 external IP 反映)
  await fs.writeFile(path.join(PJSIP_OUT_DIR, 'transports.conf'), renderTransportConfig(), 'utf-8');
  const content = await renderPjsipConfig();
  const outPath = path.join(PJSIP_OUT_DIR, 'extensions.conf');
  await fs.writeFile(outPath, content, 'utf-8');

  // Asterisk の #include は対象ファイルが無い / glob 0 件マッチで親 conf
  // 全体を parse error にする。最低 1 ファイル保証で防ぐ:
  //   - pjsip.conf -> #include "pjsip.d/trunks.conf"
  //     trunks 未設定で trunks.conf が無いと endpoint / transport / auth 全消失
  //   - extensions.conf -> #include "dialplan.d/*.conf"
  //     dialplan.d/ が空だと pbx_config declined to load → 内線→特番が Not Found
  const trunksPath = path.join(PJSIP_OUT_DIR, 'trunks.conf');
  try {
    await fs.access(trunksPath);
  } catch {
    await fs.writeFile(
      trunksPath,
      '; placeholder (no SIP trunks configured yet; /trunks Server Action overwrites this)\n',
      'utf-8',
    );
  }
  await fs.mkdir(DIALPLAN_OUT_DIR, { recursive: true });
  const dialplanPlaceholder = path.join(DIALPLAN_OUT_DIR, '_placeholder.conf');
  try {
    await fs.access(dialplanPlaceholder);
  } catch {
    await fs.writeFile(
      dialplanPlaceholder,
      '; placeholder (Asterisk #include "dialplan.d/*.conf" requires >=1 file)\n',
      'utf-8',
    );
  }

  let reloaded = false;
  try {
    await fs.mkdir(ASTERISK_SIGNAL_DIR, { recursive: true });
    await fs.writeFile(path.join(ASTERISK_SIGNAL_DIR, 'reload'), String(Date.now()), 'utf-8');
    reloaded = true;
  } catch (e) {
    console.error('[extensions] failed to signal reload', e);
  }
  return { path: outPath, reloaded };
}
