import type Database from 'better-sqlite3';
import path from 'node:path';
import fs from 'node:fs/promises';
import { getDb } from './db';
import { pickupGroupsOf } from './pickupGroups';

export interface Extension {
  number: string;
  displayName: string | null;
  secret: string;
  note: string | null;
  webrtc: boolean;
  updatedAt: string;
}

export class InvalidExtensionError extends Error {}

const NUMBER_RE = /^[0-9]{2,6}$/; // 内線番号: 2〜6桁の数字
const PJSIP_OUT_DIR = process.env.PJSIP_OUT_DIR ?? '/asterisk/pjsip.d';
const ASTERISK_SIGNAL_DIR = process.env.ASTERISK_SIGNAL_DIR ?? '/asterisk/signals';

interface ExtensionRow {
  number: string;
  display_name: string | null;
  secret: string;
  note: string | null;
  updated_at: string;
  webrtc?: number;
}

function rowToExtension(r: ExtensionRow): Extension {
  return {
    number: r.number,
    displayName: r.display_name,
    secret: r.secret,
    note: r.note,
    webrtc: !!r.webrtc,
    updatedAt: r.updated_at,
  };
}

export function listExtensions(db: Database.Database = getDb()): Extension[] {
  const rows = db
    .prepare('SELECT number, display_name, secret, note, webrtc, updated_at FROM extensions ORDER BY number')
    .all() as ExtensionRow[];
  return rows.map(rowToExtension);
}

export function getExtension(number: string, db: Database.Database = getDb()): Extension | null {
  const row = db
    .prepare('SELECT number, display_name, secret, note, webrtc, updated_at FROM extensions WHERE number = ?')
    .get(number) as ExtensionRow | undefined;
  return row ? rowToExtension(row) : null;
}

export interface UpsertExtensionInput {
  number: string;
  displayName?: string;
  secret: string;
  note?: string;
  webrtc?: boolean;
}

function validate(input: UpsertExtensionInput): void {
  if (!NUMBER_RE.test(input.number)) {
    throw new InvalidExtensionError('number は 2〜6 桁の数字で指定してください');
  }
  if (!input.secret || input.secret.length < 4) {
    throw new InvalidExtensionError('secret (パスワード) は 4 文字以上で必須です');
  }
  if (/["\\\n\r]/.test(input.secret)) {
    throw new InvalidExtensionError('secret に " \\ 改行は使えません');
  }
}

export function createExtension(input: UpsertExtensionInput, db: Database.Database = getDb()): Extension {
  validate(input);
  if (getExtension(input.number, db)) {
    throw new InvalidExtensionError(`内線 ${input.number} は既に存在します`);
  }
  db.prepare(
    `INSERT INTO extensions (number, display_name, secret, note, webrtc, updated_at)
     VALUES (?, ?, ?, ?, ?, datetime('now'))`,
  ).run(input.number, input.displayName ?? null, input.secret, input.note ?? null, input.webrtc ? 1 : 0);
  return getExtension(input.number, db)!;
}

export function updateExtension(input: UpsertExtensionInput, db: Database.Database = getDb()): Extension {
  validate(input);
  const existing = getExtension(input.number, db);
  if (!existing) {
    throw new InvalidExtensionError(`内線 ${input.number} は存在しません`);
  }
  db.prepare(
    `UPDATE extensions
        SET display_name = ?, secret = ?, note = ?, webrtc = ?, updated_at = datetime('now')
      WHERE number = ?`,
  ).run(input.displayName ?? null, input.secret, input.note ?? null, input.webrtc ? 1 : 0, input.number);
  return getExtension(input.number, db)!;
}

export function deleteExtension(number: string, db: Database.Database = getDb()): boolean {
  if (!NUMBER_RE.test(number)) {
    throw new InvalidExtensionError('number 形式が不正です');
  }
  const info = db.prepare('DELETE FROM extensions WHERE number = ?').run(number);
  return info.changes > 0;
}

// Asterisk の pjsip.d/extensions.conf を再生成する。
export async function renderPjsipConfig(): Promise<string> {
  const rows = listExtensions();
  const blocks: string[] = [
    '; AUTO-GENERATED by Web (/extensions). 手で編集しないこと。',
    `; updated_at: ${new Date().toISOString()}`,
    '',
  ];
  for (const e of rows) {
    const cidName = (e.displayName ?? `Ext ${e.number}`).replace(/"/g, '');
    const pickupNames = pickupGroupsOf(e.number);
    const templateName = e.webrtc ? 'endpoint-webrtc' : 'endpoint-internal';
    blocks.push(`[${e.number}](${templateName})`);
    blocks.push(`auth=auth${e.number}`);
    blocks.push(`aors=${e.number}`);
    blocks.push(`callerid="${cidName}" <${e.number}>`);
    if (pickupNames.length > 0) {
      blocks.push(`named_call_group=${pickupNames.join(',')}`);
      blocks.push(`named_pickup_group=${pickupNames.join(',')}`);
    }
    blocks.push('');
    blocks.push(`[auth${e.number}](auth-userpass)`);
    blocks.push(`username=${e.number}`);
    blocks.push(`password=${e.secret}`);
    blocks.push('');
    blocks.push(`[${e.number}](aor-single)`);
    blocks.push('');
  }
  return blocks.join('\n');
}

export async function writePjsipConfigAndReload(): Promise<{ path: string; reloaded: boolean }> {
  const content = await renderPjsipConfig();
  await fs.mkdir(PJSIP_OUT_DIR, { recursive: true });
  const outPath = path.join(PJSIP_OUT_DIR, 'extensions.conf');
  await fs.writeFile(outPath, content, 'utf-8');

  let reloaded = false;
  try {
    await fs.mkdir(ASTERISK_SIGNAL_DIR, { recursive: true });
    await fs.writeFile(path.join(ASTERISK_SIGNAL_DIR, 'reload'), String(Date.now()), 'utf-8');
    reloaded = true;
  } catch (e) {
    console.error('[extensions] failed to signal reload', e);
  }
  return { path: outPath, reloaded };
}
