import type Database from 'better-sqlite3';
import { getDb } from './db';
import { writeDialplanFile, signalAsteriskReload } from './dialplan';

export interface PickupGroup {
  id: number;
  name: string;
  members: string[];
  updatedAt: string;
}

export class InvalidPickupGroupError extends Error {}

const NAME_RE = /^[A-Za-z0-9_-]{1,32}$/;
const NUMBER_RE = /^[0-9]{2,6}$/;

interface Row {
  id: number;
  name: string;
  updated_at: string;
}

function loadMembers(id: number, db: Database.Database): string[] {
  return (
    db
      .prepare(
        'SELECT extension_number FROM pickup_group_members WHERE pickup_group_id = ? ORDER BY extension_number',
      )
      .all(id) as Array<{ extension_number: string }>
  ).map((r) => r.extension_number);
}

function rowToGroup(r: Row, db: Database.Database): PickupGroup {
  return { id: r.id, name: r.name, members: loadMembers(r.id, db), updatedAt: r.updated_at };
}

export function listPickupGroups(db: Database.Database = getDb()): PickupGroup[] {
  const rows = db
    .prepare('SELECT id, name, updated_at FROM pickup_groups ORDER BY name')
    .all() as Row[];
  return rows.map((r) => rowToGroup(r, db));
}

export function getPickupGroupByName(name: string, db: Database.Database = getDb()): PickupGroup | null {
  const row = db.prepare('SELECT id, name, updated_at FROM pickup_groups WHERE name = ?').get(name) as
    | Row
    | undefined;
  return row ? rowToGroup(row, db) : null;
}

// 内線番号 -> 所属する pickup group 名 (PJSIP の named_pickup_group はカンマ区切り複数可)
export function pickupGroupsOf(extensionNumber: string, db: Database.Database = getDb()): string[] {
  const rows = db
    .prepare(
      `SELECT pg.name FROM pickup_groups pg
         JOIN pickup_group_members pgm ON pgm.pickup_group_id = pg.id
        WHERE pgm.extension_number = ?
        ORDER BY pg.name`,
    )
    .all(extensionNumber) as Array<{ name: string }>;
  return rows.map((r) => r.name);
}

export interface UpsertPickupGroupInput {
  name: string;
  members?: string[];
}

function validate(input: UpsertPickupGroupInput): void {
  if (!NAME_RE.test(input.name)) {
    throw new InvalidPickupGroupError('グループ名は英数字 / _ / - のみ、1〜32 文字');
  }
  for (const m of input.members ?? []) {
    if (!NUMBER_RE.test(m)) throw new InvalidPickupGroupError(`メンバー番号が不正: ${m}`);
  }
}

export function createPickupGroup(input: UpsertPickupGroupInput, db: Database.Database = getDb()): PickupGroup {
  validate(input);
  if (getPickupGroupByName(input.name, db)) {
    throw new InvalidPickupGroupError(`ピックアップグループ ${input.name} は既に存在します`);
  }
  const info = db
    .prepare(
      `INSERT INTO pickup_groups (name, updated_at) VALUES (?, datetime('now'))`,
    )
    .run(input.name);
  const id = Number(info.lastInsertRowid);
  replaceMembers(id, input.members ?? [], db);
  return getPickupGroupByName(input.name, db)!;
}

export function updatePickupGroup(input: UpsertPickupGroupInput, db: Database.Database = getDb()): PickupGroup {
  validate(input);
  const existing = getPickupGroupByName(input.name, db);
  if (!existing) throw new InvalidPickupGroupError(`ピックアップグループ ${input.name} は存在しません`);
  db.prepare(`UPDATE pickup_groups SET updated_at = datetime('now') WHERE id = ?`).run(existing.id);
  if (input.members !== undefined) replaceMembers(existing.id, input.members, db);
  return getPickupGroupByName(input.name, db)!;
}

export function deletePickupGroup(name: string, db: Database.Database = getDb()): boolean {
  const r = db.prepare('DELETE FROM pickup_groups WHERE name = ?').run(name);
  return r.changes > 0;
}

function replaceMembers(groupId: number, members: string[], db: Database.Database): void {
  const tx = db.transaction((ms: string[]) => {
    db.prepare('DELETE FROM pickup_group_members WHERE pickup_group_id = ?').run(groupId);
    const ins = db.prepare(
      'INSERT INTO pickup_group_members (pickup_group_id, extension_number) VALUES (?, ?)',
    );
    ms.forEach((m) => ins.run(groupId, m));
  });
  tx(members);
}

// dialplan: `*8` で同じ pickup group の呼出を奪う。
// Pickup() は引数なしで呼ぶと、自分の named_pickup_group に属する全 endpoint の
// 呼出中チャネルから対象を探す。同一 context (internal) にエクステンションを追加する形で書く。
export function renderPickupDialplan(): string {
  const lines = [
    '; AUTO-GENERATED by Web (/pickup-groups).',
    `; updated_at: ${new Date().toISOString()}`,
    '',
    '[internal]',
    'exten => _*8,1,NoOp(Pickup attempt)',
    ' same => n,Pickup()',
    ' same => n,Hangup()',
    '',
  ];
  return lines.join('\n');
}

export async function writePickupDialplanAndReload(): Promise<void> {
  const content = renderPickupDialplan();
  await writeDialplanFile('pickup.conf', content);
  await signalAsteriskReload();
}
